apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tensorbeat
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/rowan-senior-project/tensorbeat-frontend:v0.2.3
        env:
          - name: PORT
            value: "50051"
          - name: ENVIRONMENT
            value: "prod"
        ports:
        - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 3000
    name: http
